name: GitHub Contributions Snake

on:
  schedule:
    - cron: '0 0 * * *'  # כל יום ב-00:00 UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install github-contribution-snake
        run: npm install -g github-contribution-grid-snake

      - name: Generate snake SVG
        run: github-contributions-snake --user RazEini

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update GitHub Contributions Snake"
          git push
